debug: true

server:
  port: "${APP_PORT:3000}"
  shutdown: graceful

spring:
  devtools:
    livereload:
      enabled: ${debug}
    restart:
      additional-exclude: "test/**"
  application:
    name: "@project.artifactId@"
  main:
    banner-mode: off
  webflux:
    problemdetails:
      enabled: true
  docker:
    compose:
      enabled: ${debug}
      file: "docker-compose.yaml"
  r2dbc:
    url: "r2dbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
  flyway:
    enabled: true
    url: "jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"
    default-schema: "${DB_SCHEMA}"
    table: "migrations"
    locations: "classpath:migrations"
    sql-migration-prefix: "0"
    sql-migration-separator: "-"
    connect-retries: 3
    connect-retries-interval: "15s"
    baseline-on-migrate: true
    fail-on-missing-locations: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
